workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      node: 18
      cocoapods: default
      xcode: latest
      
      vars:
        APPLE_TEAM_ID: "UNC2YV5NU9"

    scripts:
      - name: Build everything
        script: |
          npm ci
          npm run build
          npx cap sync ios
          cd ios/App && pod install
          
          # Archive with explicit team ID
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -allowProvisioningUpdates \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID

      - name: Export IPA
        script: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist $CM_PROJECT_DIR/export-options.plist \
            -allowProvisioningUpdates

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APPSTORE_CONNECT_PRIVATE_KEY
        key_id: $APPSTORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true