workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      node: 18
      cocoapods: default
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Next.js
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build IPA with automatic code signing
        script: |
          xcode-project build-ipa \
            --project "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-flags "-allowProvisioningUpdates" \
            --export-options-plist $CM_PROJECT_DIR/export-options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APPSTORE_CONNECT_PRIVATE_KEY
        key_id: $APPSTORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true