workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      node: 18
      cocoapods: default
      xcode: latest
      
      integrations:
        app_store_connect: "personal-apple-account"  

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Next.js
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles --project "ios/App/App.xcworkspace" --scheme "App"

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "ios/App/App.xcworkspace" \
            --scheme "App"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        # This will inherit from the integration above
        submit_to_testflight: true