workflows:
  ios_testflight:
    name: iOS TestFlight (Next.js + Capacitor)
    max_build_duration: 120

    environment:
      node: 18
      cocoapods: default
      xcode: latest

      vars:
        APPLE_ID: "nokolucky19@gmail.com"
        BUNDLE_ID: "com.billease.app.UNC2YV5NU9"  # Use a variable for consistency

      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
        # Let Codemagic automatically manage certificates
        automatic: true

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Next.js web assets
        script: |
          npm run build

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
          cd ../..

      - name: Set up code signing
        script: |
          cd ios/App
          # Ensure the project uses automatic code signing
          xcode-project use-profiles

      - name: Archive iOS build with Xcode
        script: |
          set -e
          cd ios/App

          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist $CM_PROJECT_DIR/export-options.plist

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APPSTORE_CONNECT_PRIVATE_KEY
        key_id: $APPSTORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true