workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      node: 18
      cocoapods: default
      xcode: latest
      
      # Reference your integration (use the name you gave it)
      integrations:
        app_store_connect: personal-apple-account  # Use your integration name here

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build Next.js
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Build IPA with integration
        script: |
          xcode-project build-ipa \
            --project "ios/App/App.xcworkspace" \
            --scheme "App"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        submit_to_testflight: true