workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      node: 18
      cocoapods: default
      xcode: latest
      
      integrations:
        app_store_connect: personal-apple-account

    scripts:
      - name: Set up code signing first
        script: |
          cd ios/App
          xcode-project use-profiles

      - name: Build web app
        script: |
          npm ci
          npm run build
          npx cap sync ios
          cd ios/App && pod install

      - name: Build IPA
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace "App.xcworkspace" \
            --scheme "App"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        submit_to_testflight: true