workflows:
  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      node: 18
      cocoapods: default
      xcode: latest

    scripts:
      - name: Build web app
        script: |
          npm ci
          npm run build
          npx cap sync ios

      - name: Build iOS app
        script: |
          cd ios/App
          pod install
          
          # Create simple export-options.plist
          cat > export-options.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>UNC2YV5NU9</string>
          </dict>
          </plist>
          EOF
          
          # Build with manual commands
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist export-options.plist \
            -allowProvisioningUpdates

    artifacts:
      - ios/App/build/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APPSTORE_CONNECT_PRIVATE_KEY
        key_id: $APPSTORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true