default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy do
    # Get certificates using App Store Connect API
    get_certificates(
      development: false,
      output_path: "./certs",
      username: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      team_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      api_key: app_store_connect_api_key
    )

    # Build with manual code signing
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      clean: true,
      export_options: {
        provisioningProfiles: {
          "com.billease.app.UNC2YV5NU9" => "match AppStore com.billease.app.UNC2YV5NU9"
        }
      }
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key: app_store_connect_api_key
    )
  end

  def app_store_connect_api_key
    {
      key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY'],
      is_key_content_base64: false,
      in_house: false
    }
  end
end