default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy do
    # Enable automatic code signing
    enable_automatic_code_signing(
      path: "App.xcworkspace",
      team_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      code_sign_style: "Automatic"
    )

    # Build the app
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      xcargs: "-allowProvisioningUpdates"
    )
    
    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end